### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by aallen22** [bioexcel/biobb_workflows#1]
I replaced the occurrences with the absolute path as followed:

working_dir_path: wf_abc_md_setup
can_write_console_log: False
run_md: False

step1_leap_gen_top:
  tool: leap_gen_top
  paths:
    input_pdb_path: /mnt/d/SELEX/PythonABCMDSetup/AAAAAA_ds.pdb
    output_pdb_path: structure.leap.pdb
    output_top_path: structure.leap.top
    output_crd_path: structure.leap.crd
  properties:
    forcefield: ["DNA.bsc1"] 

When attempting to run the script I get the following error:

02:54:10 step1_leap_gen_top: Generating Topology
Traceback (most recent call last):
  File "/mnt/d/SELEX/PythonABCMDSetup/workflow.py", line 133, in <module>
    main(args.config, args.system)
  File "/mnt/d/SELEX/PythonABCMDSetup/workflow.py", line 27, in main
    leap_gen_top(**global_paths["step1_leap_gen_top"], properties=global_prop["step1_leap_gen_top"])
  File "/home/aleiquea/miniconda3/envs/abc_md_setup_env/lib/python3.9/site-packages/biobb_amber/leap/leap_gen_top.py", line 241, in leap_gen_top
    return LeapGenTop( input_pdb_path=input_pdb_path,
  File "/home/aleiquea/miniconda3/envs/abc_md_setup_env/lib/python3.9/site-packages/biobb_amber/leap/leap_gen_top.py", line 105, in __init__
    self.check_arguments()
  File "/home/aleiquea/miniconda3/envs/abc_md_setup_env/lib/python3.9/site-packages/biobb_common/generic/biobb_object.py", line 84, in check_arguments
    fu.check_argument(path=Path(self.locals_var_dict[argument]) if self.locals_var_dict.get(argument) else None,
  File "/home/aleiquea/miniconda3/envs/abc_md_setup_env/lib/python3.9/site-packages/biobb_common/tools/file_utils.py", line 620, in check_argument
    raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), not_found_dir_error_string)
FileNotFoundError: [Errno 2] No such file or directory: 'Path /mnt/d/SELEX/PythonABCMDSetup/wf_abc_md_setup_3/step1_leap_gen_top --- biobb_amber.leap.leap_gen_top: Unexisting output_pdb_path directory.'

I'm not sure if I also need to change the output path or if my absolute path is inccorrect.

**Comment by PauAndrio** [comment]
Hello,

Unfortunately, We are not able to reproduce this issue, our tests running _leap_gen_top_ biobb do not show any problem. Please, could you provide us with your modified workflow and the input files?

Regards,
Pau Andrio

**Comment by aallen22** [comment]
[copyworkflow.txt](https://github.com/bioexcel/biobb_workflows/files/10404771/copyworkflow.txt)
[copy_AAAAAA_ds.txt](https://github.com/bioexcel/biobb_workflows/files/10404800/copy_AAAAAA_ds.txt)

**Comment by aallen22** [comment]
> Hello,
> 
> 
> 
> Unfortunately, We are not able to reproduce this issue, our tests running _leap_gen_top_ biobb do not show any problem. Please, could you provide us with your modified workflow and the input files?
> 
> 
> 
> Regards,
> 
> Pau Andrio

I have the same issue occurring when using WSL or Mac Unix.

**Comment by aallen22** [comment]
I've been trying to debug and I think the problem stems from the step1_biobb_curves directory not being created so the path for the output file does not exist.

**Comment by adamhospital** [comment]
Hi, 

I think we are mixing workflows here :\ 

The one you sent us previously was an MD setup, whereas in the last comment you mentioned biobb_curves which is not a setup step but an analysis one. 

I'm afraid we will need more info to try to reproduce the error. Could you please tell us briefly how did you install the BioBB library in your system and paste the content of your conda environment so we can investigate which BioBB versions were installed? 

Thanks for your interest in our tools and for your patience!
